#!/usr/bin/env bash

set -eux -o pipefail

: "${BUILDROOT_VERSION:=2022.04.26-test}"
export BUILDROOT_VERSION

mkdir -p /usr/src/buildroot

curl -fL https://github.com/cmurphy/buildroot/archive/refs/tags/${BUILDROOT_VERSION}.tar.gz | tar xz -C /usr/src/buildroot --strip-components=1
